name: y-gege
version: latest
slug: ygege
description: High-performance indexer for YGG Torrent written in Rust
url: https://github.com/RedSolos/addon-ygege
arch:
  - aarch64
  - amd64
init: false
map:
  - addon_config:rw
  - ssl
  - share:rw
ports:
  8715/tcp: 8715
ports_description:
  8715/tcp: Ygégé web interface port
image: uwucode/ygege
environment:
  YGG_USERNAME: ygg_username
  YGG_PASSWORD: ygg_password
  BIND_PORT: bind_port
  LOG_LEVEL: log_level
options:
  ygg_username: "username"
  ygg_password: "password"
  bind_port: 8715
  log_level: "info"
schema:
  ygg_username: str
  ygg_password: password
  bind_port: "port"
  log_level: "list(trace|debug|info|warn|error)"