name: Ygégé
description: High-performance indexer for YGG Torrent written in Rust
version: latest
slug: ygege
url: https://github.com/RedSolos/addon-ygege
arch:
  - aarch64
  - amd64
init: false
env:
  - LOG_LEVEL=trace
map:
  - addon_config:rw
  - share:rw
ports:
  8715/tcp: 8715
ports_description:
  8715/tcp: Ygégé web interface port
webui: http://[HOST]:[PORT:8715]
# image: uwucode/ygege
build: .
options:
  username: ""
  password: ""
schema:
  username: str
  password: str